import java.text.DateFormat
import java.text.SimpleDateFormat

plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id("org.jetbrains.kotlin.plugin.serialization") version "2.2.0"
    id 'kotlin-kapt'
}
static def buildTime() {
    DateFormat df = new SimpleDateFormat("yyyyMMddHHmm")
    return df.format(Calendar.getInstance(Locale.CHINA).getTime())
}
task downloadAndUnzipNativeLibs {
    group = 'Pre-build'
    description = 'Downloads and unzips native libraries from CDN.'
    def nativeLibsUrl = 'https://meta.alicdn.com/data/mnn/avatar/native-libs-arm64-v8a.zip'
    def zipFileName = 'avatar-native-libs-arm64-v8a.zip'
    def outputDir = project.rootDir
    def downloadedZip = new File(project.buildDir, zipFileName)
    def checkFile = new File(outputDir, 'src/main/jniLibs/arm64-v8a/libsherpa-mnn-jni.so')
    inputs.property('url', nativeLibsUrl)
    outputs.file(checkFile)
    doLast {
        println "-> Executing downloadAndUnzipNativeLibs task..."
        println "   Downloading from ${nativeLibsUrl}"
        ant.get(src: nativeLibsUrl, dest: downloadedZip)

        if (!downloadedZip.exists()) {
            throw new GradleException("Download failed: ${downloadedZip} not found.")
        }
        println "   Download complete."
        println "   Unzipping ${downloadedZip.name} to project root..."
        copy {
            from(zipTree(downloadedZip))
            into(outputDir)
        }
        println "   Unzip complete."
        downloadedZip.delete()
    }
    onlyIf {
        println "-> Checking if native libs exist... [Exists: ${checkFile.exists()}]"
        return !checkFile.exists()
    }
}
preBuild.dependsOn downloadAndUnzipNativeLibs

android {
    namespace 'com.taobao.meta.avatar'
    compileSdk 35
    ndkVersion '27.2.12479018'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += ['-Xplugin:kotlin-serialization']
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "WeloAvatar-${variant.buildType.name}-v${variant.versionName}-${buildTime()}.apk"
        }
    }

    defaultConfig {
        applicationId  "com.welo.avatar"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"

        renderscriptTargetApi 21
        renderscriptSupportModeEnabled true

        externalNativeBuild {
            cmake {
                abiFilters 'arm64-v8a'
                arguments '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=c++_shared'
            }
        }

        ndk {
            abiFilters += "arm64-v8a"
        }
    }
    externalNativeBuild {
        cmake {
            version '3.22.1'
            path 'src/main/CMakeLists.txt'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    androidResources {
        additionalParameters '--warn-manifest-validation'
    }
    buildFeatures {
        viewBinding true
    }
    buildToolsVersion '35.0.0'
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
}
ext {
    okdownload_version = '1.0.7'
    room_version = "2.6.1"
}

dependencies {
    implementation "io.ktor:ktor-client-core:2.3.3"
    implementation "io.ktor:ktor-client-okhttp:2.3.3"
    implementation "io.ktor:ktor-client-content-negotiation:2.3.3"
    implementation "io.ktor:ktor-serialization-kotlinx-json:2.3.3"
    implementation "io.ktor:ktor-client-logging:2.3.3"

    implementation 'com.google.android.material:material:1.12.0'

    implementation 'com.github.squti:Android-Wave-Recorder:2.0.1'
    implementation 'com.github.ybq:Android-SpinKit:1.4.0'

    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.activity:activity-ktx:1.8.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'

    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-scalars:2.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.3'

    implementation "com.liulishuo.okdownload:okdownload:${okdownload_version}"
    implementation "com.liulishuo.okdownload:sqlite:${okdownload_version}"
    implementation "com.liulishuo.okdownload:okhttp:${okdownload_version}"
    implementation "com.liulishuo.okdownload:filedownloader:${okdownload_version}"
    implementation "com.liulishuo.okdownload:ktx:${okdownload_version}"
    implementation 'androidx.activity:activity:1.8.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.7.7'
    implementation 'androidx.navigation:navigation-ui-ktx:2.7.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0'
    implementation 'com.airbnb.android:lottie:6.1.0'

    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.github.bumptech.glide:okhttp3-integration:4.16.0'
    implementation 'androidx.work:work-runtime-ktx:2.10.3'
    kapt 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'jp.wasabeef:glide-transformations:4.3.0'
    //流式布局
    implementation 'com.google.android.flexbox:flexbox:3.0.0'

    implementation "androidx.room:room-runtime:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    kapt  "androidx.room:room-compiler:$room_version"

    //调试okhttp请求（建议debug使用）
    implementation 'com.localebro:okhttpprofiler:1.0.8'

    implementation "io.noties.markwon:core:4.6.2"
    implementation "io.noties.markwon:image:4.6.2"
    implementation "io.noties.markwon:linkify:4.6.2"
    // 使用 Glide 插件替代 Coil
    implementation "io.noties.markwon:image-coil:4.6.2"
    implementation("io.coil-kt:coil:2.5.0")
    implementation("io.coil-kt:coil-svg:2.5.0")
    implementation("io.coil-kt:coil-gif:2.5.0")

    //Google ML Kit 语言识别
    implementation 'com.google.mlkit:language-id:17.0.4'

    implementation("com.squareup.okhttp3:okhttp-sse:4.12.0")
    //bytedance
    implementation 'com.bytedance.boringssl.so:boringssl-so:1.3.7-16kb'
    implementation('org.chromium.net:cronet:4.2.210.4-tob') {
        exclude group: 'com.bytedance.common', module: 'wschannel'
    }
    implementation 'com.bytedance.frameworks.baselib:ttnet:4.2.210.4-tob'
    implementation 'com.bytedance.speechengine:speechengine_tob:0.0.8.1-bugfix'
    implementation fileTree(include: ['*.aar'], dir: 'libs')
}
